site_name: Sunday-Generator

theme:
  name: material
  custom_dir: ../overrides

nav:
- Overview: index.md
- RAML:
  - Why?: why-raml.md
  - Extensions: raml-extensions.md
- Targets:
  - Common Features: target-common-features.md
  - Kotlin:
    - Common Features: target-kotlin-common-features.md
    - Sunday: kotlin-sunday.md
    - JAX-RS: kotlin-jaxrs.md
  - Swift:
    - Common Features: target-swift-common-features.md
    - Sunday: swift-sunday.md
  - TypeScript:
    - Common Features: target-typescript-common-features.md    
    - Sunday: typescript-sunday.md
- API: api.md

repo_url: https://github.com/outfoxx/sunday-generator
