site_name: Sunday

theme:
  name: material
  custom_dir: overrides
  feature:
  - navigation.expand
  - navigation.instant
  - navigation.indexes
  - navigation.tracking
  - navigation.top
  - search.suggest
  - search.highlight
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
  palette:
  - scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to light mode
  - scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode

extra_css:
  - stylesheets/custom.css

nav:
- Overview:
  - About: index.md
  - Features:
    - Detailed Error Responses via Problems: problems.md
    - Efficient Notifications via Server-Sent Events: server-sent-events.md
    - Dynamic Content-Type Negotation: dynamic-content-type-negotiation.md
    - Alternative Request/Response Encodings: alternative-request-response-encodings.md
    - Date/Time Data Types: date-time-data-types.md
    - Simple & Beautiful Code: client-code.md
- Generator: '!include ./generator/mkdocs.yml'
- Client Libraries:
  - Swift Package: '!include ./sunday-swift/mkdocs.yml'
  - Kotlin Library: '!include ./sunday-kotlin/mkdocs.yml'
  - TypeScript Package: '!include ./sunday-js/mkdocs.yml'

copyright: Copyright &copy; 2021 Outfox, Inc.

markdown_extensions:
- admonition
- attr_list
- def_list
- md_in_html
- footnotes
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.superfences
- pymdownx.caret
- pymdownx.details
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
- monorepo
- search
- macros


extra:
  homepage: https://outfoxx.io
  generator:
    latest_release: 1.1.0-beta.2
  client:
    swift:
      latest_release: 1.0.0-beta.13
    kotlin:
      latest_release: 1.0.0-beta.18
    typescript:
      latest_release: 1.1.0-beta.5
